import { BiLogoPostgresql } from "react-icons/bi";
import { BsFillBootstrapFill } from "react-icons/bs";
import { FaNpm, FaPython, FaJava, FaAngular, FaReact, FaDocker, FaAws, FaGoogle, FaMicrosoft } from "react-icons/fa6";
import {
  SiCss3,
  SiExpress,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiNextdotjs,
  SiNodedotjs,
  SiPrisma,
  SiReact,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiRedux,
  SiVuedotjs,
  SiFirebase,
  SiReacthookform,
  SiMysql,
  SiMongodb,
  SiYarn,
  SiNestjs,
  SiDocker,
  SiNuxtdotjs,
  SiAngular,
  SiWebpack,
  SiFormik,
  SiChakraui,
  SiAntdesign,
  SiStyledcomponents,
  SiSass,
  SiRedis,
  SiGraphql,
  SiApollographql,
  SiSocketdotio,
  SiAmazon,
  SiGooglecloud,
  SiVercel,
  SiRender,
  SiPnpm,
  SiEslint,
  SiPrettier,
  SiGit,
  SiGitlab,
  SiPostman,
  SiFigma,
  SiMarkdown,
} from "react-icons/si";

export type SkillProps = {
  [key: string]: {
    icon: JSX.Element;
    background: string;
    color: string;
    isActive?: boolean;
  };
};

const iconSize = 26;

export const STACKS: SkillProps = {
  JavaScript: {
    icon: <SiJavascript size={iconSize} />,
    background: "bg-yellow-500",
    color: "text-yellow-500",
    isActive: true,
  },
  TypeScript: {
    icon: <SiTypescript size={iconSize} />,
    background: "bg-blue-600",
    color: "text-blue-600",
    isActive: true,
  },
  Python: {
    icon: <FaPython size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  },
  Java: {
    icon: <FaJava size={iconSize} />,
    background: "bg-red-600",
    color: "text-red-600",
    isActive: true,
  },
  React: {
    icon: <SiReact size={iconSize} />,
    background: "bg-cyan-500",
    color: "text-cyan-500",
    isActive: true,
  },
  "Next.js": {
    icon: <SiNextdotjs size={iconSize} />,
    background: "bg-black",
    color: "text-black",
    isActive: true,
  },
  "Vue.js": {
    icon: <SiVuedotjs size={iconSize} />,
    background: "bg-green-500",
    color: "text-green-500",
    isActive: true,
  },
  "Nuxt.js": {
    icon: <SiNuxtdotjs size={iconSize} />,
    background: "bg-green-600",
    color: "text-green-600",
    isActive: true,
  },
  Angular: {
    icon: <SiAngular size={iconSize} />,
    background: "bg-red-600",
    color: "text-red-600",
    isActive: true,
  },
  Vite: {
    icon: <SiVite size={iconSize} />,
    background: "bg-purple-500",
    color: "text-purple-500",
    isActive: true,
  },
  Webpack: {
    icon: <SiWebpack size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  },
  Redux: {
    icon: <SiRedux size={iconSize} />,
    background: "bg-purple-600",
    color: "text-purple-600",
    isActive: true,
  },
  "React Hook Form": {
    icon: <SiReacthookform size={iconSize} />,
    background: "bg-pink-500",
    color: "text-pink-500",
    isActive: true,
  },
  Formik: {
    icon: <SiFormik size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  },
  "Tailwind CSS": {
    icon: <SiTailwindcss size={iconSize} />,
    background: "bg-cyan-500",
    color: "text-cyan-500",
    isActive: true,
  },
  "Chakra UI": {
    icon: <SiChakraui size={iconSize} />,
    background: "bg-green-500",
    color: "text-teal-500",
    isActive: true,
  },
  "Ant Design": {
    icon: <SiAntdesign size={iconSize} />,
    background: "bg-blue-600",
    color: "text-blue-600",
    isActive: true,
  },
  Bootstrap: {
    icon: <BsFillBootstrapFill size={iconSize} />,
    background: "bg-purple-600",
    color: "text-purple-600",
    isActive: true,
  },
  "Styled Components": {
    icon: <SiStyledcomponents size={iconSize} />,
    background: "bg-pink-500",
    color: "text-pink-500",
    isActive: true,
  },
  SCSS: {
    icon: <SiSass size={iconSize} />,
    background: "bg-pink-500",
    color: "text-pink-500",
    isActive: true,
  },
  "Node.js": {
    icon: <SiNodedotjs size={iconSize} />,
    background: "bg-green-600",
    color: "text-green-600",
    isActive: true,
  },
  "Express.js": {
    icon: <SiExpress size={iconSize} />,
    background: "bg-gray-600",
    color: "text-gray-600",
    isActive: true,
  },
  NestJS: {
    icon: <SiNestjs size={iconSize} />,
    background: "bg-pink-500",
    color: "text-pink-500",
    isActive: true,
  },
  MongoDB: {
    icon: <SiMongodb size={iconSize} />,
    background: "bg-green-600",
    color: "text-green-600",
    isActive: true,
  },
  PostgreSQL: {
    icon: <BiLogoPostgresql size={iconSize} />,
    background: "bg-blue-600",
    color: "text-blue-600",
    isActive: true,
  },
  MySQL: {
    icon: <SiMysql size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  },
  Redis: {
    icon: <SiRedis size={iconSize} />,
    background: "bg-red-600",
    color: "text-red-600",
    isActive: true,
  },
  Prisma: {
    icon: <SiPrisma size={iconSize} />,
    background: "bg-gray-800",
    color: "text-gray-800",
    isActive: true,
  },
  Firebase: {
    icon: <SiFirebase size={iconSize} />,
    background: "bg-orange-500",
    color: "text-orange-500",
    isActive: true,
  },
  GraphQL: {
    icon: <SiGraphql size={iconSize} />,
    background: "bg-pink-500",
    color: "text-pink-500",
    isActive: true,
  },
  "Apollo GraphQL": {
    icon: <SiApollographql size={iconSize} />,
    background: "bg-purple-600",
    color: "text-purple-600",
    isActive: true,
  },
  "Socket.io": {
    icon: <SiSocketdotio size={iconSize} />,
    background: "bg-black",
    color: "text-black",
    isActive: true,
  },
  Docker: {
    icon: <SiDocker size={iconSize} />,
    background: "bg-blue-600",
    color: "text-blue-600",
    isActive: true,
  },
  AWS: {
    icon: <SiAmazon size={iconSize} />,
    background: "bg-orange-500",
    color: "text-orange-500",
    isActive: true,
  },
  "Google Cloud": {
    icon: <SiGooglecloud size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  },
  Azure: {
    icon: <FaMicrosoft size={iconSize} />,
    background: "bg-blue-600",
    color: "text-blue-600",
    isActive: true,
  },
  Vercel: {
    icon: <SiVercel size={iconSize} />,
    background: "bg-black",
    color: "text-black",
    isActive: true,
  },
  Render: {
    icon: <SiRender size={iconSize} />,
    background: "bg-orange-500",
    color: "text-orange-500",
    isActive: true,
  },
  npm: {
    icon: <FaNpm size={iconSize} />,
    background: "bg-red-600",
    color: "text-red-600",
    isActive: true,
  },
  Yarn: {
    icon: <SiYarn size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  },
  pnpm: {
    icon: <SiPnpm size={iconSize} />,
    background: "bg-orange-500",
    color: "text-orange-500",
    isActive: true,
  },
  ESLint: {
    icon: <SiEslint size={iconSize} />,
    background: "bg-purple-600",
    color: "text-purple-600",
    isActive: true,
  },
  Prettier: {
    icon: <SiPrettier size={iconSize} />,
    background: "bg-gray-800",
    color: "text-gray-800",
    isActive: true,
  },
  Git: {
    icon: <SiGit size={iconSize} />,
    background: "bg-orange-600",
    color: "text-orange-600",
    isActive: true,
  },
  GitHub: {
    icon: <SiGithub size={iconSize} />,
    background: "bg-black",
    color: "text-black",
    isActive: true,
  },
  GitLab: {
    icon: <SiGitlab size={iconSize} />,
    background: "bg-orange-600",
    color: "text-orange-600",
    isActive: true,
  },
  Postman: {
    icon: <SiPostman size={iconSize} />,
    background: "bg-orange-500",
    color: "text-orange-500",
    isActive: true,
  },
  Figma: {
    icon: <SiFigma size={iconSize} />,
    background: "bg-purple-500",
    color: "text-purple-500",
    isActive: true,
  },
  HTML5: {
    icon: <SiHtml5 size={iconSize} />,
    background: "bg-orange-500",
    color: "text-orange-500",
    isActive: true,
  },
  CSS3: {
    icon: <SiCss3 size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  },
  Markdown: {
    icon: <SiMarkdown size={iconSize} />,
    background: "bg-gray-600",
    color: "text-gray-600",
    isActive: true,
  },
};
